- project:
    name: openstack/puppet-ceph
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - puppet-openstack-integration-jobs-scenario001
      - puppet-openstack-integration-jobs-scenario004
